"""Added availability records to DB
Revision ID: 0c4f8abf03c0
Revises: 818137c56e00
Create Date: 2022-05-11 13:05:41.538464
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '0c4f8abf03c0'
down_revision = '818137c56e00'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('frequency', sa.String(length=1), nullable=True),
    sa.Column('com_class_code_id', sa.String(length=16), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('is_partner_detail', sa.Boolean(), nullable=True),
    sa.Column('inserted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['com_class_code_id'], ['comm_class_code.code_class'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['country.country_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_record_com_class_code_id'), 'availability_record', ['com_class_code_id'], unique=False)
    op.create_index(op.f('ix_availability_record_frequency'), 'availability_record', ['frequency'], unique=False)
    op.create_index(op.f('ix_availability_record_inserted'), 'availability_record', ['inserted'], unique=False)
    op.create_index(op.f('ix_availability_record_period'), 'availability_record', ['period'], unique=False)
    op.create_index(op.f('ix_availability_record_reporter_id'), 'availability_record', ['reporter_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availability_record_reporter_id'), table_name='availability_record')
    op.drop_index(op.f('ix_availability_record_period'), table_name='availability_record')
    op.drop_index(op.f('ix_availability_record_inserted'), table_name='availability_record')
    op.drop_index(op.f('ix_availability_record_frequency'), table_name='availability_record')
    op.drop_index(op.f('ix_availability_record_com_class_code_id'), table_name='availability_record')
    op.drop_table('availability_record')
    # ### end Alembic commands ###