"""Size increase
Revision ID: 570e3f4e6024
Revises: 9348392480f9
Create Date: 2022-05-11 15:41:58.088177
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = '570e3f4e6024'
down_revision = '9348392480f9'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commodity', 'description',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.create_unique_constraint(None, 'country', ['country_id'])
    op.create_unique_constraint(None, 'cst_code', ['code'])
    op.create_unique_constraint(None, 'flow_code', ['code'])
    op.create_unique_constraint(None, 'mos_code', ['code'])
    op.create_unique_constraint(None, 'mot_code', ['code'])
    op.create_unique_constraint(None, 'quantity_code', ['code'])
    op.create_unique_constraint(None, 'rg_code', ['code'])
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rg_code', type_='unique')
    op.drop_constraint(None, 'quantity_code', type_='unique')
    op.drop_constraint(None, 'mot_code', type_='unique')
    op.drop_constraint(None, 'mos_code', type_='unique')
    op.drop_constraint(None, 'flow_code', type_='unique')
    op.drop_constraint(None, 'cst_code', type_='unique')
    op.drop_constraint(None, 'country', type_='unique')
    op.alter_column('commodity', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###